@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class CalcularINSS {
  + CalcularINSS(): 
  - calcParcela(FolhaContexto): double
  - calcAliquota(FolhaContexto): double
  + calcularImposto(FolhaContexto): void
}
class CalcularIR {
  + CalcularIR(): 
  + calcularImposto(FolhaContexto): void
  - calcAliquota(double): double
  - calcParcela(double): double
}
interface CalcularImposto << interface >> {
  + calcularImposto(FolhaContexto): void
}
class Departamento {
  + Departamento(int, String): 
  + Departamento(int): 
  + Departamento(String): 
  - id: int
  - nome: String
  + toString(): String
   nome: String
   id: int
}
class Dependente {
  + Dependente(String, String, LocalDate, Parentesco, Funcionario): 
  - parentesco: Parentesco
  - funcionario: Funcionario
   funcionario: Funcionario
   parentesco: Parentesco
}
class FolhaLoteService {
  + FolhaLoteService(): 
  - escreverCSV(FolhaPagamento): String
  + processarLote(String, String): void
  - processarEscrever(FolhaPagamentoService, Funcionario, FolhaContexto, BufferedWriter, Connection): void
}
class FolhaPagamento {
  + FolhaPagamento(): 
  + FolhaPagamento(Funcionario, double, double, double): 
  - salarioLiquido: double
  - funcionario: Funcionario
  - data: LocalDate
  - INSS: double
   IR: double
   data: LocalDate
   funcionario: Funcionario
   salarioLiquido: double
   INSS: double
}
class FolhaPagamentoService {
  + FolhaPagamentoService(): 
  + folhaCalculo(Funcionario): FolhaPagamento
  + folhaCalculo(Funcionario, FolhaContexto): FolhaPagamento
}
class Funcionario {
  + Funcionario(String, String, LocalDate, double, Departamento): 
  - salarioBruto: double
  - departamento: Departamento
  - dependentes: List<Dependente>
   departamento: Departamento
   salarioBruto: double
   dependentes: List<Dependente>
}
class Main {
  + Main(): 
  + main(String[]): void
}
class Pessoa {
  + Pessoa(String, LocalDate, String): 
  - nascimento: LocalDate
  - nome: String
  - cpf: String
   cpf: String
   nome: String
   nascimento: LocalDate
}
class node1 as "package  br.com.folhapag.config" << package >>
class node2 as "package  br.com.folhapag.contexts" << package >>
class node4 as "package  br.com.folhapag.dao" << package >>
class node5 as "package  br.com.folhapag.enums" << package >>
class node0 as "package  br.com.folhapag.exceptions" << package >>
class node6 as "package  br.com.folhapag.utils" << package >>
class node7 as "package  br.com.folhapag.views" << package >>

CalcularINSS           -[#008200,dashed]-^  CalcularImposto       
CalcularIR             -[#008200,dashed]-^  CalcularImposto       
Dependente            "1" *-[#595959,plain]-> "funcionario\n1" Funcionario           
Dependente             -[#000082,plain]-^  Pessoa                
FolhaLoteService       -[#595959,dashed]->  FolhaPagamentoService : "«create»"
FolhaLoteService       -[#595959,dashed]->  Funcionario           : "«create»"
FolhaPagamento        "1" *-[#595959,plain]-> "funcionario\n1" Funcionario           
FolhaPagamentoService "1" *-[#595959,plain]-> "INSS\n1" CalcularINSS          
FolhaPagamentoService  -[#595959,dashed]->  CalcularINSS          : "«create»"
FolhaPagamentoService  -[#595959,dashed]->  CalcularIR            : "«create»"
FolhaPagamentoService "1" *-[#595959,plain]-> "IRRF\n1" CalcularIR            
FolhaPagamentoService  -[#595959,dashed]->  FolhaPagamento        : "«create»"
Funcionario           "1" *-[#595959,plain]-> "departamento\n1" Departamento          
Funcionario           "1" *-[#595959,plain]-> "dependentes\n*" Dependente            
Funcionario            -[#000082,plain]-^  Pessoa                
@enduml
